# Generated by Django 4.2.7 on 2026-01-13 22:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Numéro de facture"),
                ),
                (
                    "total_ppa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total PPA",
                    ),
                ),
                (
                    "total_shp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Total SHP",
                    ),
                ),
                (
                    "net_to_pay",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Net à payer",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Date de facture")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Mois")),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.supplier",
                        verbose_name="Fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "db_table": "invoices_invoices",
                "ordering": ["-invoice_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier"], name="invoices_in_supplie_aa47a8_idx"
                    ),
                    models.Index(
                        fields=["invoice_date"], name="invoices_in_invoice_bf9295_idx"
                    ),
                    models.Index(
                        fields=["month", "year"], name="invoices_in_month_51308f_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="invoices_in_is_acti_d792a5_idx"
                    ),
                ],
                "unique_together": {("supplier", "invoice_number")},
            },
        ),
    ]
