# Generated by Django 4.2.7 on 2026-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
    ]
