# Generated by Django 4.2.7 on 2026-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="total_ppa",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_shp",
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("PENDING", "En attente"), ("PAID", "Payé")],
                default="DRAFT",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
    ]
