# Generated by Django 4.2.7 on 2026-01-13 22:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credit_note_number",
                    models.CharField(max_length=100, verbose_name="Numéro d'avoir"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                ("credit_note_date", models.DateField(verbose_name="Date d'avoir")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Mois")),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="suppliers.supplier",
                        verbose_name="Fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avoir",
                "verbose_name_plural": "Avoirs",
                "db_table": "credit_notes_credit_notes",
                "ordering": ["-credit_note_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier"], name="credit_note_supplie_c0bff5_idx"
                    ),
                    models.Index(
                        fields=["credit_note_date"],
                        name="credit_note_credit__14285e_idx",
                    ),
                    models.Index(
                        fields=["month", "year"], name="credit_note_month_6a3b6f_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="credit_note_is_acti_c6c872_idx"
                    ),
                ],
            },
        ),
    ]
