# Generated by Django 4.2.7 on 2026-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="motif",
            field=models.TextField(blank=True, null=True, verbose_name="Motif"),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Brouillon"), ("PENDING", "En attente"), ("APPLIED", "Appliqué")],
                default="DRAFT",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
