# Generated by Django 4.2.7 on 2026-01-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_notes", "0002_creditnote_motif_status"),
        ("invoices", "0003_remove_invoice_totals_add_status_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes",
                to="invoices.invoice",
                verbose_name="Facture associée",
            ),
        ),
    ]
