# Generated by Django 4.2.7 on 2026-01-16 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("credit_notes", "0003_creditnote_invoice_fk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditnote",
            name="status",
        ),
    ]
