# Generated by Django 4.2.7 on 2026-01-13 22:29

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nom du fournisseur"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code doit contenir uniquement des majuscules et chiffres (3-20 caractères)",
                                regex="^[A-Z0-9]{3,20}$",
                            )
                        ],
                        verbose_name="Code fournisseur",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le code postal doit contenir 5 chiffres",
                                regex="^[0-9]{5}$",
                            )
                        ],
                        verbose_name="Code postal",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format de téléphone invalide",
                                regex="^[0-9+\\s()-]{10,20}$",
                            )
                        ],
                        verbose_name="Téléphone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le SIRET doit contenir 14 chiffres",
                                regex="^[0-9]{14}$",
                            )
                        ],
                        verbose_name="SIRET",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Personne de contact",
                    ),
                ),
                (
                    "payment_terms",
                    models.IntegerField(
                        default=30, verbose_name="Délai de paiement (jours)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "suppliers_suppliers",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="suppliers_s_name_b467d5_idx"),
                    models.Index(fields=["code"], name="suppliers_s_code_3c9602_idx"),
                    models.Index(
                        fields=["is_active"], name="suppliers_s_is_acti_9c2146_idx"
                    ),
                    models.Index(fields=["siret"], name="suppliers_s_siret_59c2dd_idx"),
                ],
            },
        ),
    ]
