# Generated by Django 4.2.7 on 2026-01-14 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le code doit contenir uniquement des majuscules et chiffres (3-20 caractères)",
                        regex="^[A-Z0-9]{3,20}$",
                    )
                ],
                verbose_name="Code fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="siret",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le SIRET doit contenir 14 chiffres",
                        regex="^[0-9]{14}$",
                    )
                ],
                verbose_name="SIRET",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="payment_terms",
            field=models.IntegerField(
                blank=True,
                null=True,
                default=30,
                verbose_name="Délai de paiement (jours)",
            ),
        ),
    ]
